name: 'Terragrunt Check'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true
    env:
      tg_version: ${{ github.event.inputs.tg_version || 'default_version' }}

jobs:
  perform-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Install Terragrunt'
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${{ env.tg_version }}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: 'Check Terragrunt configuration'
        run: terragrunt hclfmt --terragrunt-check --terragrunt-diff
        working-directory: ${{ inputs.working_dir }}
