name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true


jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}

  terragrunt-project-plan:
    uses: ./.github/workflows/plan.yml
    with:
      working_dir: ${{ inputs.working_dir }}
    secrets: inherit
    needs: [ terragrunt-project-check ]