name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true

env:
  tf_version: 1.9.5
  tg_version: 0.53.2

jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}
      tg_version: ${{ env.tg_version }}
