name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true

env:
  tf_version: 1.9.5
  tg_version: v0.53.2

jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}

  terragrunt-plan:
    uses: ./.github/workflows/plan.yml
    with:
      working_dir: ${{ inputs.working_dir }}
    needs: terragrunt-project-check