name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true


jobs:
  terragrunt-pipeline:
    runs-on: ubuntu-latest
    steps:
      # Run the check workflow
      - name: 'Run Terragrunt Check'
        uses: ./.github/workflows/check.yml
        with:
          working_dir: ${{ inputs.working_dir }}