name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true


jobs:
  project:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}