name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true

env:
  tf_version: '1.5.7'   # Define Terraform version once
  tg_version: '0.53.2'   # Define Terragrunt version once


jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}
      tf_version: ${{ env.tf_version }}  # Pass version from parent
      tg_version: ${{ env.tg_version }}  # Pass version from parent
