name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true
      tg_version:
        type: string
        required: true

jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}
      tg_version: ${{ inputs.tg_version }}
