name: 'Terragrunt CI/CD Pipeline'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true
      tf_version:
        required: true
      tg_version:
        required: true


jobs:
  terragrunt-project-check:
    uses: ./.github/workflows/check.yml
    with:
      working_dir: ${{ inputs.working_dir }}

  terragrunt-project-plan:
    uses: ./.github/workflows/plan.yml
    with:
      working_dir: ${{ inputs.working_dir }}
    secrets: inherit
    needs: [ terragrunt-project-check ]

  terragrunt-project-apply:
    uses: ./.github/workflows/deploy.yml
    with:
      working_dir: ${{ inputs.working_dir }}
      tf_version: ${{ inputs.tf_version }}
      tg_version: ${{ inputs.tg_version }}
    secrets: inherit
    needs: [ terragrunt-project-plan ]