name: 'Terragrunt Plan'

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true

jobs:
  perform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set default terragrunt version'
        id: defaults
        run: |
          echo "tg_version=${{ github.event.inputs.tg_version || 'v0.53.2' }}" >> $GITHUB_ENV
          echo "tf_version=${{ github.event.inputs.tf_version || '1.9.5' }}" >> $GITHUB_ENV

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false

      - name: 'Install Terragrunt'
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: 'Run Terragrunt plan'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        run: terragrunt plan
        working-directory: ${{ inputs.working_dir }}
